apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rp56ewvxo-java-quarkus
  janus-idp.io/tekton: rp56ewvxo-java-quarkus
  backstage.io/kubernetes-id: rp56ewvxo-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rp56ewvxo-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
